<script setup>
import ShareCardModelVue from "./components/shareCardModel.vue";
const shareArray=[
  {
    "id": 1,
    "hairType": "微分碎盖",
    "userId": 1,
    "description": "这个发型我真的太爱了，发行也很不错，大家快冲",
    "shopName": "潮club工作室",
    "shopId": 2,
    "location": "山东",
    "title": "今日发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["微分碎盖", "潮club"],
    "type": "日常分享",
    "createTime": "2020.01.02"
  },
  {
    "id": 2,
    "hairType": "层次短发",
    "userId": 2,
    "description": "新发型新气象，赶紧预约试试看",
    "shopName": "时尚发艺",
    "shopId": 3,
    "location": "广东",
    "title": "最新发型推荐",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["层次短发", "时尚发艺"],
    "type": "店铺分享",
    "createTime": "2020.01.03"
  },
  {
    "id": 3,
    "hairType": "长直发",
    "userId": 3,
    "description": "今天做了长直发，感觉轻松了许多",
    "shopName": "美丽天地",
    "shopId": 4,
    "location": "北京",
    "title": "发型心得分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["长直发", "美丽天地"],
    "type": "日常分享",
    "createTime": "2020.01.04"
  },
  {
    "id": 4,
    "hairType": "复古卷发",
    "userId": 4,
    "description": "复古风格总是让人回味无穷",
    "shopName": "时尚美发",
    "shopId": 5,
    "location": "上海",
    "title": "经典发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["复古卷发", "时尚美发"],
    "type": "日常分享",
    "createTime": "2020.01.05"
  },
  {
    "id": 5,
    "hairType": "短发造型",
    "userId": 5,
    "description": "试了一个新的短发造型，感觉清爽了很多",
    "shopName": "流行造型屋",
    "shopId": 6,
    "location": "湖南",
    "title": "时尚造型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["短发造型", "流行造型屋"],
    "type": "日常分享",
    "createTime": "2020.01.06"
  },
  {
    "id": 6,
    "hairType": "中分长发",
    "userId": 6,
    "description": "中分长发永远是时尚的代表",
    "shopName": "潮流美发屋",
    "shopId": 7,
    "location": "广西",
    "title": "经典发型推荐",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["中分长发", "潮流美发屋"],
    "type": "日常分享",
    "createTime": "2020.01.07"
  },
  {
    "id": 7,
    "hairType": "短发设计",
    "userId": 7,
    "description": "短发设计总是能给人惊喜",
    "shopName": "时尚设计师",
    "shopId": 8,
    "location": "福建",
    "title": "最新发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["短发设计", "时尚设计师"],
    "type": "店铺分享",
    "createTime": "2020.01.08"
  },
  {
    "id": 8,
    "hairType": "儿童编发",
    "userId": 8,
    "description": "孩子的发型也可以很有创意哦",
    "shopName": "童趣发型屋",
    "shopId": 9,
    "location": "浙江",
    "title": "童趣发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["儿童编发", "童趣发型屋"],
    "type": "日常分享",
    "createTime": "2020.01.09"
  },
  {
    "id": 9,
    "hairType": "男士修剪",
    "userId": 9,
    "description": "男士修剪，精致而不失阳刚之美",
    "shopName": "时尚男士理发店",
    "shopId": 10,
    "location": "湖北",
    "title": "男士发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["男士修剪", "时尚男士理发店"],
    "type": "店铺分享",
    "createTime": "2020.01.10"
  },
  {
    "id": 10,
    "hairType": "韩式烫发",
    "userId": 10,
    "description": "韩式烫发，清新自然，时尚动人",
    "shopName": "韩式发艺",
    "shopId": 11,
    "location": "河北",
    "title": "烫发新体验",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["韩式烫发", "韩式发艺"],
    "type": "日常分享",
    "createTime": "2020.01.11"
  },
  {
    "id": 11,
    "hairType": "波浪长发",
    "userId": 11,
    "description": "波浪长发，气质满满，让人心动",
    "shopName": "时尚发廊",
    "shopId": 12,
    "location": "四川",
    "title": "浪漫发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["波浪长发", "时尚发廊"],
    "type": "店铺分享",
    "createTime": "2020.01.12"
  },
  {
    "id": 12,
    "hairType": "简约短发",
    "userId": 12,
    "description": "简约短发，干净利落，时尚百搭",
    "shopName": "简约美发屋",
    "shopId": 13,
    "location": "山西",
    "title": "简约发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["简约短发", "简约美发屋"],
    "type": "日常分享",
    "createTime": "2020.01.13"
  },
  {
    "id": 13,
    "hairType": "发带搭配",
    "userId": 13,
    "description": "发带搭配，时尚又可爱，让发型更有特色",
    "shopName": "时尚发饰店",
    "shopId": 14,
    "location": "江苏",
    "title": "发饰新搭配",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["发带搭配", "时尚发饰店"],
    "type": "日常分享",
    "createTime": "2020.01.14"
  },
  {
    "id": 14,
    "hairType": "蓬松短发",
    "userId": 14,
    "description": "蓬松短发，动感十足，时尚舒适",
    "shopName": "动感美发",
    "shopId": 15,
    "location": "山东",
    "title": "活力发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["蓬松短发", "动感美发"],
    "type": "店铺分享",
    "createTime": "2020.01.15"
  },
  {
    "id": 15,
    "hairType": "女士编发",
    "userId": 15,
    "description": "女士编发，优雅精致，时尚气质",
    "shopName": "优雅发饰",
    "shopId": 16,
    "location": "广东",
    "title": "优雅发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["女士编发", "优雅发饰"],
    "type": "店铺分享",
    "createTime": "2020.01.16"
  },
  {
    "id": 16,
    "hairType": "婚礼发型",
    "userId": 16,
    "description": "婚礼发型，浪漫唯美，梦幻般的体验",
    "shopName": "梦幻发艺",
    "shopId": 17,
    "location": "北京",
    "title": "梦幻婚礼造型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["婚礼发型", "梦幻发艺"],
    "type": "店铺分享",
    "createTime": "2020.01.17"
  },
  {
    "id": 17,
    "hairType": "潮流烫发",
    "userId": 17,
    "description": "潮流烫发，个性十足，时尚无限",
    "shopName": "个性发型屋",
    "shopId": 18,
    "location": "上海",
    "title": "个性发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["潮流烫发", "个性发型屋"],
    "type": "店铺分享",
    "createTime": "2020.01.18"
  },
  {
    "id": 18,
    "hairType": "刘海短发",
    "userId": 18,
    "description": "刘海短发，清新可爱，时尚百搭",
    "shopName": "清新美发屋",
    "shopId": 19,
    "location": "江西",
    "title": "清新发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["刘海短发", "清新美发屋"],
    "type": "日常分享",
    "createTime": "2020.01.19"
  },
  {
    "id": 19,
    "hairType": "学生发型",
    "userId": 19,
    "description": "学生发型，活泼可爱，时尚新潮",
    "shopName": "时尚发型学校",
    "shopId": 20,
    "location": "湖南",
    "title": "学生时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["学生发型", "时尚发型学校"],
    "type": "日常分享",
    "createTime": "2020.01.20"
  },
  {
    "id": 20,
    "hairType": "休闲发型",
    "userId": 20,
    "description": "休闲发型，自然舒适，时尚潮流",
    "shopName": "休闲美发屋",
    "shopId": 21,
    "location": "广西",
    "title": "休闲时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["休闲发型", "休闲美发屋"],
    "type": "日常分享",
    "createTime": "2020.01.21"
  },
  {
    "id": 21,
    "hairType": "时尚短发",
    "userId": 21,
    "description": "时尚短发，个性张扬，时尚前卫",
    "shopName": "时尚造型",
    "shopId": 22,
    "location": "福建",
    "title": "时尚短发分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["时尚短发", "时尚造型"],
    "type": "店铺分享",
    "createTime": "2020.01.22"
  },
  {
    "id": 22,
    "hairType": "夏日发型",
    "userId": 22,
    "description": "夏日发型，清凉舒爽，时尚美丽",
    "shopName": "夏日发型屋",
    "shopId": 23,
    "location": "浙江",
    "title": "夏日时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["夏日发型", "夏日发型屋"],
    "type": "日常分享",
    "createTime": "2020.01.23"
  },
  {
    "id": 23,
    "hairType": "假发定制",
    "userId": 23,
    "description": "假发定制，打造不同风格，时尚独特",
    "shopName": "时尚假发店",
    "shopId": 24,
    "location": "山东",
    "title": "时尚假发分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["假发定制", "时尚假发店"],
    "type": "日常分享",
    "createTime": "2020.01.24"
  },
  {
    "id": 24,
    "hairType": "复古发型",
    "userId": 24,
    "description": "复古发型，怀旧复古，时尚潮流",
    "shopName": "复古造型",
    "shopId": 25,
    "location": "广东",
    "title": "复古风发型分享",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["复古发型", "复古造型"],
    "type": "店铺分享",
    "createTime": "2020.01.25"
  },
  {
    "id": 25,
    "hairType": "职业发型",
    "userId": 25,
    "description": "职业发型，干练大气，时尚精致",
    "shopName": "职业造型屋",
    "shopId": 26,
    "location": "上海",
    "title": "职业时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["职业发型", "职业造型屋"],
    "type": "日常分享",
    "createTime": "2020.01.26"
  },
  {
    "id": 26,
    "hairType": "晚宴发型",
    "userId": 26,
    "description": "晚宴发型，高贵典雅，时尚迷人",
    "shopName": "高贵发艺",
    "shopId": 27,
    "location": "河北",
    "title": "晚宴时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["晚宴发型", "高贵发艺"],
    "type": "店铺分享",
    "createTime": "2020.01.27"
  },
  {
    "id": 27,
    "hairType": "情人节发型",
    "userId": 27,
    "description": "情人节发型，甜蜜浪漫，时尚动人",
    "shopName": "浪漫美发",
    "shopId": 28,
    "location": "四川",
    "title": "情人节时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["情人节发型", "浪漫美发"],
    "type": "日常分享",
    "createTime": "2020.01.28"
  },
  {
    "id": 28,
    "hairType": "婚纱发型",
    "userId": 28,
    "description": "婚纱发型，唯美大气，时尚独特",
    "shopName": "婚纱发艺",
    "shopId": 29,
    "location": "江苏",
    "title": "婚纱时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["婚纱发型", "婚纱发艺"],
    "type": "店铺分享",
    "createTime": "2020.01.29"
  },
  {
    "id": 29,
    "hairType": "女士烫发",
    "userId": 29,
    "description": "女士烫发，优雅时尚，气质非凡",
    "shopName": "优雅美发",
    "shopId": 30,
    "location": "湖北",
    "title": "优雅时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["女士烫发", "优雅美发"],
    "type": "日常分享",
    "createTime": "2020.01.30"
  },
  {
    "id": 30,
    "hairType": "假发修复",
    "userId": 30,
    "description": "假发修复，恢复新颜，重焕时尚",
    "shopName": "假发修复中心",
    "shopId": 31,
    "location": "四川",
    "title": "时尚假发修复",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["假发修复", "假发修复中心"],
    "type": "店铺分享",
    "createTime": "2020.01.31"
  },
  {
    "id": 31,
    "hairType": "可爱发型",
    "userId": 31,
    "description": "可爱发型，活泼可爱，时尚新潮",
    "shopName": "可爱发型屋",
    "shopId": 32,
    "location": "广东",
    "title": "可爱时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["可爱发型", "可爱发型屋"],
    "type": "日常分享",
    "createTime": "2020.02.01"
  },
  {
    "id": 32,
    "hairType": "儿童发型",
    "userId": 32,
    "description": "儿童发型，童趣满满，时尚新颖",
    "shopName": "童趣发型",
    "shopId": 33,
    "location": "广西",
    "title": "童趣时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["儿童发型", "童趣发型"],
    "type": "日常分享",
    "createTime": "2020.02.02"
  },
  {
    "id": 33,
    "hairType": "清新发型",
    "userId": 33,
    "description": "清新发型，清新可爱，时尚新潮",
    "shopName": "清新美发",
    "shopId": 34,
    "location": "山西",
    "title": "清新时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["清新发型", "清新美发"],
    "type": "店铺分享",
    "createTime": "2020.02.03"
  },
  {
    "id": 34,
    "hairType": "韩系短发",
    "userId": 34,
    "description": "韩系短发，时尚新潮，清新可爱",
    "shopName": "韩风发型",
    "shopId": 35,
    "location": "福建",
    "title": "韩风时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["韩系短发", "韩风发型"],
    "type": "日常分享",
    "createTime": "2020.02.04"
  },
  {
    "id": 35,
    "hairType": "运动发型",
    "userId": 35,
    "description": "运动发型，轻松时尚，活力满满",
    "shopName": "运动发型屋",
    "shopId": 36,
    "location": "江苏",
    "title": "运动时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["运动发型", "运动发型屋"],
    "type": "日常分享",
    "createTime": "2020.02.05"
  },
  {
    "id": 36,
    "hairType": "清新短发",
    "userId": 36,
    "description": "清新短发，清新可爱，时尚新潮",
    "shopName": "清新美发",
    "shopId": 37,
    "location": "广东",
    "title": "清新时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["清新短发", "清新美发"],
    "type": "日常分享",
    "createTime": "2020.02.06"
  },
  {
    "id": 37,
    "hairType": "男士发型",
    "userId": 37,
    "description": "男士发型，时尚新潮，干练大气",
    "shopName": "时尚男士发型",
    "shopId": 38,
    "location": "湖南",
    "title": "时尚男士发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["男士发型", "时尚男士发型"],
    "type": "店铺分享",
    "createTime": "2020.02.07"
  },
  {
    "id": 38,
    "hairType": "清新长发",
    "userId": 38,
    "description": "清新长发，优雅时尚，气质非凡",
    "shopName": "清新美发",
    "shopId": 39,
    "location": "山东",
    "title": "清新时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["清新长发", "清新美发"],
    "type": "日常分享",
    "createTime": "2020.02.08"
  },
  {
    "id": 39,
    "hairType": "波浪短发",
    "userId": 39,
    "description": "波浪短发，时尚新潮，清新可爱",
    "shopName": "时尚发型",
    "shopId": 40,
    "location": "广西",
    "title": "时尚波浪发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["波浪短发", "时尚发型"],
    "type": "日常分享",
    "createTime": "2020.02.09"
  },
  {
    "id": 40,
    "hairType": "甜美发型",
    "userId": 40,
    "description": "甜美发型，甜蜜可爱，清新新潮",
    "shopName": "甜美发型屋",
    "shopId": 41,
    "location": "福建",
    "title": "甜美时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["甜美发型", "甜美发型屋"],
    "type": "日常分享",
    "createTime": "2020.02.10"
  },
  {
    "id": 41,
    "hairType": "女士短发",
    "userId": 41,
    "description": "女士短发，时尚新潮，清新可爱",
    "shopName": "时尚发型",
    "shopId": 42,
    "location": "北京",
    "title": "时尚女士发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["女士短发", "时尚发型"],
    "type": "日常分享",
    "createTime": "2020.02.11"
  },
  {
    "id": 42,
    "hairType": "婚纱造型",
    "userId": 42,
    "description": "婚纱造型，唯美浪漫，甜蜜如画",
    "shopName": "甜蜜婚纱",
    "shopId": 43,
    "location": "四川",
    "title": "甜蜜婚纱造型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["婚纱造型", "甜蜜婚纱"],
    "type": "店铺分享",
    "createTime": "2020.02.12"
  },
  {
    "id": 43,
    "hairType": "日系发型",
    "userId": 43,
    "description": "日系发型，清新可爱，时尚新潮",
    "shopName": "日系发型屋",
    "shopId": 44,
    "location": "湖北",
    "title": "日系时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["日系发型", "日系发型屋"],
    "type": "日常分享",
    "createTime": "2020.02.13"
  },
  {
    "id": 44,
    "hairType": "优雅发型",
    "userId": 44,
    "description": "优雅发型，气质非凡，时尚典雅",
    "shopName": "优雅发型",
    "shopId": 45,
    "location": "江苏",
    "title": "优雅时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["优雅发型", "优雅发型"],
    "type": "日常分享",
    "createTime": "2020.02.14"
  },
  {
    "id": 45,
    "hairType": "夏日发型",
    "userId": 45,
    "description": "夏日发型，清凉舒爽，时尚美丽",
    "shopName": "夏日发型屋",
    "shopId": 46,
    "location": "四川",
    "title": "夏日时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["夏日发型", "夏日发型屋"],
    "type": "店铺分享",
    "createTime": "2020.02.15"
  },
  {
    "id": 46,
    "hairType": "清新短发",
    "userId": 46,
    "description": "清新短发，时尚新潮，清新可爱",
    "shopName": "清新美发",
    "shopId": 47,
    "location": "福建",
    "title": "清新时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["清新短发", "清新美发"],
    "type": "日常分享",
    "createTime": "2020.02.16"
  },
  {
    "id": 47,
    "hairType": "潮流发型",
    "userId": 47,
    "description": "潮流发型，时尚新潮，个性张扬",
    "shopName": "时尚发型",
    "shopId": 48,
    "location": "广东",
    "title": "潮流时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["潮流发型", "时尚发型"],
    "type": "日常分享",
    "createTime": "2020.02.17"
  },
  {
    "id": 48,
    "hairType": "波浪长发",
    "userId": 48,
    "description": "波浪长发，气质满满，时尚动人",
    "shopName": "时尚发型",
    "shopId": 49,
    "location": "湖南",
    "title": "波浪时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["波浪长发", "时尚发型"],
    "type": "日常分享",
    "createTime": "2020.02.18"
  },
  {
    "id": 49,
    "hairType": "休闲发型",
    "userId": 49,
    "description": "休闲发型，自然舒适，时尚潮流",
    "shopName": "时尚发型",
    "shopId": 50,
    "location": "四川",
    "title": "休闲时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["休闲发型", "时尚发型"],
    "type": "日常分享",
    "createTime": "2020.02.19"
  },
  {
    "id": 50,
    "hairType": "复古发型",
    "userId": 50,
    "description": "复古发型，怀旧复古，时尚潮流",
    "shopName": "时尚发型",
    "shopId": 51,
    "location": "江苏",
    "title": "复古时尚发型",
    "imgs": "https://img2.imgtp.com/2024/04/13/IjkjcvVF.jpg",
    "searchInfo": ["复古发型", "时尚发型"],
    "type": "日常分享",
    "createTime": "2020.02.20"
  }]


</script>
<template>
  <div id="shareBox">
    <div v-for="(item,i) in shareArray" :key="item.id" class="share">
      <ShareCardModelVue
        :shareBody="item"
      ></ShareCardModelVue>
    </div>
  </div>
</template>

<style lang="scss" scoped>
#shareBox{
  display: flex;
  flex-wrap: wrap;
}

</style>